// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-9HMF-7i7AUIEiQGqu3Xg2zTEflvZuI',
    appId: '1:919019903604:web:53715a789cb82dec6a0f21',
    messagingSenderId: '919019903604',
    projectId: 'lifestable-project',
    authDomain: 'lifestable-project.firebaseapp.com',
    storageBucket: 'lifestable-project.firebasestorage.app',
    measurementId: 'G-NVR7WK20PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6NvbgSs4TRnYN0lZf1hlfbFt7VKygR_A',
    appId: '1:919019903604:android:43d6d009c61fba336a0f21',
    messagingSenderId: '919019903604',
    projectId: 'lifestable-project',
    storageBucket: 'lifestable-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUh99SXOp9PUP5HVrHKDBesr22MLVqtrc',
    appId: '1:919019903604:ios:b61c582612cbd0976a0f21',
    messagingSenderId: '919019903604',
    projectId: 'lifestable-project',
    storageBucket: 'lifestable-project.firebasestorage.app',
    iosBundleId: 'com.example.projectLifestable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUh99SXOp9PUP5HVrHKDBesr22MLVqtrc',
    appId: '1:919019903604:ios:b61c582612cbd0976a0f21',
    messagingSenderId: '919019903604',
    projectId: 'lifestable-project',
    storageBucket: 'lifestable-project.firebasestorage.app',
    iosBundleId: 'com.example.projectLifestable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr-9HMF-7i7AUIEiQGqu3Xg2zTEflvZuI',
    appId: '1:919019903604:web:8f8d3f78e7ba34ec6a0f21',
    messagingSenderId: '919019903604',
    projectId: 'lifestable-project',
    authDomain: 'lifestable-project.firebaseapp.com',
    storageBucket: 'lifestable-project.firebasestorage.app',
    measurementId: 'G-YYBTH8E2YW',
  );
}
