import 'package:flutter/material.dart';

final localeNotifier = ValueNotifier<Locale>(const Locale('en'));

class S {
  static final Map<String, Map<String, String>> _data = {
    'en': {
      'welcome_back': 'Welcome\nback.',
      'sign_in_subtitle': 'Sign in to continue your journey.',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'sign_in': 'Sign In',
      'or_continue_with': 'or continue with',
      'continue_with_google': 'Continue with Google',
      'no_account': "Don't have an account? ",
      'create_one': 'Create one',
      'create_account_title': 'Create\naccount.',
      'create_account_subtitle': 'Start building a stable life today.',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'create_account_btn': 'Create Account',
      'already_have_account': 'Already have an account? ',
      'sign_in_link': 'Sign in',
      'forgot_password_title': 'Forgot\npassword?',
      'forgot_password_subtitle': "No worries, we'll send you reset instructions.",
      'send_reset_link': 'Send Reset Link',
      'back_to_sign_in': 'Back to Sign In',
      'check_email_title': 'Check your\nemail.',
      'check_email_subtitle': "We've sent a password reset link to your email.",
      'email_required': 'Email and password are required.',
      'passwords_no_match': 'Passwords do not match.',
      'fill_all_fields': 'Please fill all required fields.',
      'name_hint': 'John Doe',
      'email_hint': 'you@example.com',
      'auth_config_error': 'Firebase Auth configuration not found.',
      'invalid_credentials': 'Invalid email or password.',
      'invalid_email': 'Invalid email address.',
      'op_not_allowed': 'Email/Password sign-in is not enabled.',
      'sign_in_failed': 'Sign in failed.',
      'email_in_use': 'This email is already in use.',
      'weak_password': 'Password is too weak.',
      'register_failed': 'Account creation failed.',
      'two': 'two',
      // Dashboard & Menu
      'calendar': 'Calendar',
      'todo_list': 'To-Do List',
      'team': 'Team',
      'ai_bot': 'AI Bot',
      'habits': 'Habits',
      'add_location': 'Add Location',
      'settings': 'Settings',
      'logout': 'Log Out',
      'streak_tracker': 'Streak Tracker',
      'days': 'days',
      'active': 'active',
      'no_habits_yet': 'No habits yet.',
      'deadlines_today': 'You Have {count} Deadlines Today.',
      'fast_summary': 'Fast Summary',
      'all_clear_today': 'All clear today!',
      'tasks_today': 'You have {count} tasks today.',
      'next_up': 'Next up:',
      'close_deadlines': 'Close Deadlines',
      'all_clear': 'All clear!',
      'high': 'HIGH',
      'med': 'MED',
      'low': 'LOW',
      'todays_focus': "Today's Focus",
      'no_events_today': 'No events today',
      'daily_insights': 'DAILY INSIGHTS (AI)',
      'ai_summarizing': 'Summarizing your daily progress...',
      'no_domains_yet': 'No domains yet',
      'tasks_count': '{count} tasks',
      'task_count': '{count} task',
      'day_count': '{count} day',
      'days_count': '{count} days',
      'dashboard': 'Dashboard',
      'habit': 'Habit',
      'todo': 'TO DO',
      'doing': 'DOING',
      'done': 'DONE',
      'delete': 'Delete',
      'no_tasks_found': 'No tasks found for this domain.',
      'no_tasks_team': 'No tasks found for this team.',
      'task_conflict_msg': 'Conflict detected — another member updated this task. Pull to refresh.',
      // Settings
      'calendar_sync': 'Calendar Sync',
      'google_calendar': 'Google Calendar',
      'connected': 'Connected',
      'not_connected': 'Not connected',
      'disconnect': 'Disconnect',
      'sync_now': 'Sync now',
      'connect': 'Connect',
      'sync_complete': 'Sync complete',
      'created': 'Created',
      'updated': 'Updated',
      'deleted': 'Deleted',
      'disconnect_confirm_title': 'Disconnect Google Calendar',
      'disconnect_confirm_msg': 'This removes the Google connection and sync mappings. Imported events already in LifeStable will stay unless you delete them manually.',
      'cancel': 'Cancel',
      'language': 'Language',
      'connect_failed': 'Connect failed: {error}',
      'sync_failed': 'Sync failed: {error}',
      'browser_opened': 'Browser opened. After approving access, return to the app.',
      'could_not_open_google': 'Could not open the Google sign-in page.',
      'google_calendar_desc': 'Connect your Google Calendar to import events into LifeStable.',
      'settings_desc': 'This MVP imports events from Google Calendar into your LifeStable calendar.',
      // Assistant
      'assistant_title': 'LifeStable AI',
      'assistant_subtitle': 'Always here for you',
      'assistant_welcome_title': 'Hello!\nHow Can I Help You?',
      'assistant_welcome_subtitle': 'You can ask me anything about\nyour tasks, habits, or calendar.',
      'assistant_help_prompt': 'What can I help you with?',
      'ai_thinking': 'AI is thinking...',
      'type_message': 'Type your message',
      'image_processing_coming': 'Image processing coming soon.',
      'suggest_summarize': '📋  Summarize my day',
      'suggest_tasks': '⏰  Upcoming tasks',
      'suggest_lighter_day': '📅  Find a lighter day this week',
      'suggest_habits': '🔥  Today\'s habits',
      'suggest_add_task': '➕  How do I add a task?',
      'suggest_how_to_use': '💡  How do I use the app?',
      // Habits
      'habit_tracker': 'HABIT TRACKER',
      'new_habit': 'New Habit',
      'habit_name': 'Habit Name',
      'add': 'Add',
      'delete_habit_title': 'Delete Habit',
      'delete_habit_confirm': 'Delete "{name}"?',
      // Calendar
      'calendar_title': 'CALENDAR',
      'month_week': 'Month / Week',
      'day_view': 'Day View',
      'new_event': 'New Event',
      'import_schedule': 'Import Course Schedule',
      'choose_gallery': 'Choose from Gallery',
      'take_photo': 'Take a Photo',
      'no_courses_found': 'No courses found in image.',
      'confirm_schedule': 'Confirm Schedule',
      'toggle_import': 'Toggle events you want to import:',
      'repeat_weeks': 'Repeat for how many weeks?',
      'weeks': 'weeks',
      'add_to_calendar': 'Add to Calendar',
      'delete_event_title': 'Delete event?',
      'delete_event_confirm': 'Remove "{title}"?',
      'team_event_delete_warning': 'This is a team event — it will be removed for everyone.',
      'event_type_personal': 'Personal',
      'event_type_task': 'Task',
      'event_type_class': 'Class',
      'event_type_team': 'Team',
      'event_count': '{count} event',
      'events_count': '{count} events',
      'conflict_count': '{count} conflict',
      'conflicts_count': '{count} conflicts',
      'member_count': '{count} member',
      'members_count': '{count} members',
      'linked_task': 'Linked task',
      // Tasks
      'board': 'BOARD',
      'create_task': 'Create Task',
      'edit_task': 'Edit Task',
      'task_title': 'Task Title',
      'task_title_hint': 'Task title',
      'description_hint': 'Optional description',
      'domain': 'Domain',
      'select_domain': 'Select domain',
      'priority': 'Priority',
      'due_date': 'Due Date',
      'select_date': 'Select date',
      'save_task': 'Save Task',
      'required_field': 'Required',
      'please_select_domain': 'Please select a domain',
      'ai_magic_task': 'AI Magic Task',
      'ai_prompt_hint': 'e.g. Add go to market for tomorrow 8pm',
      'ai_thinking_short': 'AI is thinking...',
      'task_created_ai': 'Task created by AI! ✨',
      'event_created_ai': 'Calendar event created by AI! 📅',
      'ai_error_understanding': 'AI could not understand or created an event.',
      'magic_btn': 'Magic!',
      'status_todo': 'To-Do',
      'status_doing': 'Doing',
      'status_done': 'Done',
      'priority_high': 'High',
      'priority_medium': 'Medium',
      'priority_low': 'Low',
      // Teams
      'team_dashboard': 'Team Dashboard',
      'join_with_code': 'Join with Code',
      'create_team': 'Create Team',
      'team_name': 'Team Name',
      'objective_optional': 'Objective (optional)',
      'team_color': 'Team Color',
      'no_teams_yet': 'No teams yet.',
      'create_or_join_desc': 'Create one or join with a code.',
      'team_created_title': 'Team Created!',
      'share_invite_code': 'Share this invite code with your teammates:',
      'invite_code_copied': 'Invite code copied!',
      'tap_to_copy': 'Tap to copy',
      'ok': 'OK',
      'enter_invite_code': 'Enter Invite Code',
      'join_team': 'Join Team',
      'invalid_code': 'Invalid invite code',
      'already_in_team': 'You are already a member of this team',
      'join_success': 'Successfully joined the team!',
      'team_details': 'Team Details',
      'members': 'Members',
      'leave_team': 'Leave Team',
      'leave_team_confirm': 'Are you sure you want to leave this team?',
      'leave': 'Leave',
      // Domains
      'edit_domain': 'Edit Domain',
      'new_domain': 'New Domain',
      'domain_desc_hint': 'Create a new life domain to organize your tasks.',
      'domain_name': 'Domain Name',
      'domain_name_hint': 'e.g., School, Health, Work',
      'domain_description': 'Description (Optional)',
      'domain_description_hint': 'What is this domain about?',
      'icon': 'Icon',
      'color': 'Color',
      'create_domain': 'Create Domain',
      'owner': 'Owner',
      'admin': 'Admin',
      'member': 'Member',
      'member_actions': 'Member Actions',
      'make_admin': 'Make Admin',
      'remove_admin': 'Remove Admin',
      'transfer_ownership': 'Transfer Ownership',
      'remove_from_team': 'Remove from Team',
      'delete_team': 'Delete Team',
      'delete_team_confirm': 'This will permanently delete the team and remove all members. Are you sure?',
      'transfer_ownership_confirm': 'You will become an admin. The selected user will become the new owner.',
      'new_code_generated': 'New invite code generated!',
      'camera_permission_required': 'Camera permission is required.',
      'photo_permission_required': 'Photo library permission is required.',
      'mic_permission_required': 'Microphone permission is required.',
      'speech_not_available': 'Speech recognition is not available on this device.',
      'no_notes_yet': 'No notes yet.',
      'please_sign_in_notes': 'Please sign in to use notes.',
      'notes': 'Notes',
      'save': 'Save',
      'delete_location_title': 'Delete Location',
      'radius': 'Radius',
      'dont_remind_after': 'Don\'t remind after',
      'pick_location_first': 'Please search or pick a location first.',
      'enter_label': 'Please enter a label.',
      'fetching_location': 'Fetching device location...',
      'debug_disabled_release': 'Debug tools disabled in release builds.',
      'no_triggers_today': 'No triggers today.',
      'no_locations_saved': 'No locations saved.',
      'export_summary': 'Export Summary',
      'skip_reasons': 'SKIP REASONS',
      'map_placeholder': 'Map Placeholder (no real map yet)',
      'map': 'Map',
      'alerts_placeholder': 'Alerts Placeholder',
      'alerts': 'Alerts',
      'no_team': '— No team —',
      'select_team': 'Select a team',
      'time_conflict': 'Time Conflict',
      'save_anyway': 'Save Anyway',
      'select_task_link': 'Select a task to link',
      'no_linked_task': '— No linked task —',
      'delete_event': 'Delete Event',
      'action_undone_warning': 'This action cannot be undone.',
      'task_detail': 'Task Detail',
      'task_detail_placeholder': 'Task Detail Placeholder',
      'error_prefix': 'Error: {message}',
      'add_task': 'Add Task',
      'last_sync': 'Last sync: {date}',
      'connected_at': 'Connected at: {date}',
      'synced_from_team': 'Synced from team',
      'balance_your_life': 'Balance your life.',
      'add_note': 'Add Note',
      'edit_note': 'Edit Note',
      'unnamed': 'Unnamed',
      'title': 'Title',
      'content': 'Content',
      'disconnected': 'Disconnected',
      'account': 'account',
      'disconnect_failed': 'Disconnect failed: {error}',
      'failed_to_create_event': 'Failed to create event: {error}',
      'geofence_debug_tool': 'Geofence Debug Tool',
      'geofences': 'GEOFENCES',
      'last_trigger_logs': 'LAST 10 TRIGGER LOGS (today)',
      'simulate_enter': 'Simulate Enter',
      'simulate_exit': 'Simulate Exit',
      'inside': 'INSIDE',
      'outside': 'OUTSIDE',
      'sent': '✓ sent',
      'skipped': '✗ {reason}',
      'edit_location': 'Edit Location',
      'search_address_hint': 'Search address…',
      'address_not_found': 'Address not found. Try a different query.',
      'location_label_hint': 'Label (e.g. School, Gym, Market)',
      'on_arrival': 'On Arrival',
      'on_leave': 'On Leave',
      'not_set': 'Not set',
      'save_changes': 'Save Changes',
      'save_location': 'Save Location',
      'locations': 'Locations',
      'show_map': 'Show Map',
      'saved_locations': 'Saved Locations',
      'you_are_here': 'You are here',
      'radius_m': '{radius} m radius',
      'pin_on_map_hint': 'Tap on the map to pin a location',
      'pin_on_map': 'Pin on Map',
      'edit': 'Edit',
      'delete_location_confirm': 'Remove "{label}" from saved locations?',
      'no_locations_yet': 'No saved locations yet.\nTap the map to add one.',
      'get_started': 'Get Started',
      'tagline': 'Build habits.\nLive intentionally.',
      'notification_channel_location_name': 'Location Alerts',
      'notification_channel_team_name': 'Team Updates',
      'notification_channel_team_desc': 'Notifications for team board changes',
      'notification_arrived_at': '📍 Arrived at {location}',
      'notification_left': '👋 Left {location}',
      'notification_arrived_body': "You've arrived at {location}! Check your tasks here.",
      'notification_left_body': "You've left {location}.",
      'notification_reminder_title': '⏰ Reminder: {location}',
      'notification_reminder_body': "You arrived at {location} 30 minutes ago. Don't forget your tasks!",
      'ai_config_error': 'System configuration missing (API Key not found).',
      'ai_default_response': 'Action completed.',
      'ai_error_generic': 'An error occurred.',
    },
    'tr': {
      'welcome_back': 'Tekrar\nhoş geldin.',
      'sign_in_subtitle': 'Yolculuğuna devam et.',
      'email': 'E-posta',
      'password': 'Şifre',
      'forgot_password': 'Şifremi unuttum?',
      'sign_in': 'Giriş Yap',
      'or_continue_with': 'veya şununla devam et',
      'continue_with_google': 'Google ile Devam Et',
      'no_account': 'Hesabın yok mu? ',
      'create_one': 'Oluştur',
      'create_account_title': 'Hesap\noluştur.',
      'create_account_subtitle': 'Dengeli bir hayat kurmaya başla.',
      'full_name': 'Ad Soyad',
      'confirm_password': 'Şifreyi Onayla',
      'create_account_btn': 'Hesap Oluştur',
      'already_have_account': 'Zaten hesabın var mı? ',
      'sign_in_link': 'Giriş yap',
      'forgot_password_title': 'Şifreni mi\nunuttun?',
      'forgot_password_subtitle': 'Endişelenme, sıfırlama talimatları göndereceğiz.',
      'send_reset_link': 'Sıfırlama Bağlantısı Gönder',
      'back_to_sign_in': 'Girişe Dön',
      'check_email_title': 'E-postanı\nkontrol et.',
      'check_email_subtitle': 'Şifre sıfırlama bağlantısı e-posta adresine gönderildi.',
      'email_required': 'E-posta ve şifre gereklidir.',
      'passwords_no_match': 'Şifreler eşleşmiyor.',
      'fill_all_fields': 'Lütfen tüm alanları doldurun.',
      'name_hint': 'Ad Soyad',
      'email_hint': 'siz@ornek.com',
      'auth_config_error': 'Firebase Kimlik Doğrulama yapılandırması bulunamadı.',
      'invalid_credentials': 'Geçersiz e-posta veya şifre.',
      'invalid_email': 'Geçersiz e-posta adresi.',
      'op_not_allowed': 'E-posta/Şifre ile giriş etkin değil.',
      'sign_in_failed': 'Giriş başarısız.',
      'email_in_use': 'Bu e-posta zaten kullanımda.',
      'weak_password': 'Şifre çok zayıf.',
      'register_failed': 'Hesap oluşturma başarısız.',
      'two': 'iki',
      // Dashboard & Menu
      'calendar': 'Takvim',
      'todo_list': 'Yapılacaklar',
      'team': 'Ekip',
      'ai_bot': 'AI Bot',
      'habits': 'Alışkanlıklar',
      'add_location': 'Konum Ekle',
      'settings': 'Ayarlar',
      'logout': 'Çıkış Yap',
      'streak_tracker': 'Seri Takibi',
      'days': 'gün',
      'active': 'aktif',
      'no_habits_yet': 'Henüz alışkanlık yok.',
      'deadlines_today': 'Bugün {count} Teslim Tarihiniz Var.',
      'fast_summary': 'Hızlı Özet',
      'all_clear_today': 'Bugün her şey yolunda!',
      'tasks_today': 'Bugün {count} göreviniz var.',
      'next_up': 'Sıradaki:',
      'close_deadlines': 'Yaklaşan Teslimler',
      'all_clear': 'Her şey tamam!',
      'high': 'YÜKSEK',
      'med': 'ORTA',
      'low': 'DÜŞÜK',
      'todays_focus': 'Günün Odağı',
      'no_events_today': 'Bugün etkinlik yok',
      'daily_insights': 'GÜNLÜK ANALİZ (AI)',
      'ai_summarizing': 'Günlük ilerlemeniz özetleniyor...',
      'no_domains_yet': 'Henüz alan yok',
      'tasks_count': '{count} görev',
      'task_count': '{count} görev',
      'day_count': '{count} gün',
      'days_count': '{count} gün',
      'dashboard': 'Panel',
      'habit': 'Alışkanlık',
      'todo': 'YAPILACAK',
      'doing': 'YAPILIYOR',
      'done': 'TAMAMLANDI',
      'delete': 'Sil',
      'no_tasks_found': 'Bu alan için görev bulunamadı.',
      'no_tasks_team': 'Bu ekip için görev bulunamadı.',
      'task_conflict_msg': 'Çakışma tespit edildi — başka bir üye bu görevi güncelledi. Yenilemek için kaydırın.',
      // Settings
      'calendar_sync': 'Takvim Senkronizasyonu',
      'google_calendar': 'Google Takvim',
      'connected': 'Bağlı',
      'not_connected': 'Bağlı değil',
      'disconnect': 'Bağlantıyı Kes',
      'sync_now': 'Şimdi senkronize et',
      'connect': 'Bağlan',
      'sync_complete': 'Senkronizasyon tamamlandı',
      'created': 'Oluşturuldu',
      'updated': 'Güncellendi',
      'deleted': 'Silindi',
      'disconnect_confirm_title': 'Google Takvim Bağlantısını Kes',
      'disconnect_confirm_msg': 'Bu işlem Google bağlantısını ve senkronizasyon eşleşmelerini kaldırır. LifeStable\'a aktarılmış etkinlikler manuel olarak silmedikçe kalacaktır.',
      'cancel': 'İptal',
      'language': 'Dil',
      'connect_failed': 'Bağlantı hatası: {error}',
      'sync_failed': 'Senkronizasyon hatası: {error}',
      'browser_opened': 'Tarayıcı açıldı. Erişimi onayladıktan sonra uygulamaya dönün.',
      'could_not_open_google': 'Google giriş sayfası açılamadı.',
      'google_calendar_desc': 'Etkinlikleri LifeStable\'a aktarmak için Google Takviminizi bağlayın.',
      'settings_desc': 'Bu sürüm Google Takvim etkinliklerini LifeStable takviminize aktarır.',
      // Assistant
      'assistant_title': 'LifeStable AI',
      'assistant_subtitle': 'Her zaman yanınızda',
      'assistant_welcome_title': 'Merhaba!\nNasıl Yardımcı Olabilirim?',
      'assistant_welcome_subtitle': 'Bana görevlerin, alışkanlıkların veya takvimin hakkında her şeyi sorabilirsin.',
      'assistant_help_prompt': 'Size ne konuda yardımcı olabilirim?',
      'ai_thinking': 'AI düşünüyor...',
      'type_message': 'Mesajınızı yazın',
      'image_processing_coming': 'Görüntü işleme yakında eklenecek.',
      'suggest_summarize': '📋  Günümü özetle',
      'suggest_tasks': '⏰  Yaklaşan görevler',
      'suggest_lighter_day': '📅  Bu hafta daha sakin bir gün bul',
      'suggest_habits': '🔥  Bugünkü alışkanlıklar',
      'suggest_add_task': '➕  Nasıl görev eklerim?',
      'suggest_how_to_use': '💡  Uygulamayı nasıl kullanırım?',
      // Habits
      'habit_tracker': 'ALIŞKANLIK TAKİBİ',
      'new_habit': 'Yeni Alışkanlık',
      'habit_name': 'Alışkanlık Adı',
      'add': 'Ekle',
      'delete_habit_title': 'Alışkanlığı Sil',
      'delete_habit_confirm': '"{name}" alışkanlığını silmek istiyor musunuz?',
      // Calendar
      'calendar_title': 'TAKVİM',
      'month_week': 'Ay / Hafta',
      'day_view': 'Gün Görünümü',
      'new_event': 'Yeni Etkinlik',
      'import_schedule': 'Ders Programı İçe Aktar',
      'choose_gallery': 'Galeriden Seç',
      'take_photo': 'Fotoğraf Çek',
      'no_courses_found': 'Görüntüde ders bulunamadı.',
      'confirm_schedule': 'Programı Onayla',
      'toggle_import': 'İçe aktarmak istediğiniz etkinlikleri seçin:',
      'repeat_weeks': 'Kaç hafta tekrarlansın?',
      'weeks': 'hafta',
      'add_to_calendar': 'Takvime Ekle',
      'delete_event_title': 'Etkinliği sil?',
      'delete_event_confirm': '"{title}" etkinliğini kaldırmak istiyor musunuz?',
      'team_event_delete_warning': 'Bu bir ekip etkinliğidir — herkes için kaldırılacaktır.',
      'event_type_personal': 'Kişisel',
      'event_type_task': 'Görev',
      'event_type_class': 'Ders',
      'event_type_team': 'Ekip',
      'event_count': '{count} etkinlik',
      'events_count': '{count} etkinlik',
      'conflict_count': '{count} çakışma',
      'conflicts_count': '{count} çakışma',
      'member_count': '{count} üye',
      'members_count': '{count} üye',
      'linked_task': 'Bağlı görev',
      // Tasks
      'board': 'PANO',
      'create_task': 'Görev Oluştur',
      'edit_task': 'Görevi Düzenle',
      'task_title': 'Görev Başlığı',
      'task_title_hint': 'Görev başlığı',
      'description_hint': 'İsteğe bağlı açıklama',
      'domain': 'Alan (Domain)',
      'select_domain': 'Alan seçin',
      'priority': 'Öncelik',
      'due_date': 'Teslim Tarihi',
      'select_date': 'Tarih seçin',
      'save_task': 'Görevi Kaydet',
      'required_field': 'Gerekli',
      'please_select_domain': 'Lütfen bir alan seçin',
      'ai_magic_task': 'AI Sihirli Görev',
      'ai_prompt_hint': 'Örn: Yarın akşam 8 için markete gitmeyi ekle',
      'ai_thinking_short': 'AI düşünüyor...',
      'task_created_ai': 'Görev AI tarafından oluşturuldu! ✨',
      'event_created_ai': 'Takvim etkinliği AI tarafından oluşturuldu! 📅',
      'ai_error_understanding': 'AI anlayamadı veya bir etkinlik oluşturdu.',
      'magic_btn': 'Sihir!',
      'status_todo': 'Yapılacak',
      'status_doing': 'Yapılıyor',
      'status_done': 'Tamamlandı',
      'priority_high': 'Yüksek',
      'priority_medium': 'Orta',
      'priority_low': 'Düşük',
      // Teams
      'team_dashboard': 'Ekip Paneli',
      'join_with_code': 'Kodla Katıl',
      'create_team': 'Ekip Oluştur',
      'team_name': 'Ekip Adı',
      'objective_optional': 'Hedef (isteğe bağlı)',
      'team_color': 'Ekip Rengi',
      'no_teams_yet': 'Henüz ekip yok.',
      'create_or_join_desc': 'Bir ekip oluşturun veya kodla katılın.',
      'team_created_title': 'Ekip Oluşturuldu!',
      'share_invite_code': 'Bu davet kodunu ekip arkadaşlarınızla paylaşın:',
      'invite_code_copied': 'Davet kodu kopyalandı!',
      'tap_to_copy': 'Kopyalamak için dokunun',
      'ok': 'Tamam',
      'enter_invite_code': 'Davet Kodunu Girin',
      'join_team': 'Ekibe Katıl',
      'invalid_code': 'Geçersiz davet kodu',
      'already_in_team': 'Zaten bu ekibin üyesisiniz',
      'join_success': 'Ekibe başarıyla katıldınız!',
      'team_details': 'Ekip Detayları',
      'members': 'Üyeler',
      'leave_team': 'Ekipten Ayrıl',
      'leave_team_confirm': 'Bu ekipten ayrılmak istediğinize emin misiniz?',
      'leave': 'Ayrıl',
      // Domains
      'edit_domain': 'Alanı Düzenle',
      'new_domain': 'Yeni Alan',
      'domain_desc_hint': 'Görevlerinizi düzenlemek için yeni bir yaşam alanı oluşturun.',
      'domain_name': 'Alan Adı',
      'domain_name_hint': 'Örn: Okul, Sağlık, İş',
      'domain_description': 'Açıklama (İsteğe Bağlı)',
      'domain_description_hint': 'Bu alan ne hakkında?',
      'icon': 'İkon',
      'color': 'Renk',
      'create_domain': 'Alan Oluştur',
      'owner': 'Sahip',
      'admin': 'Yönetici',
      'member': 'Üye',
      'member_actions': 'Üye İşlemleri',
      'make_admin': 'Yönetici Yap',
      'remove_admin': 'Yöneticiliği Kaldır',
      'transfer_ownership': 'Sahipliği Devret',
      'remove_from_team': 'Ekipten Çıkar',
      'delete_team': 'Ekibi Sil',
      'delete_team_confirm': 'Bu işlem ekibi kalıcı olarak silecek ve tüm üyeleri çıkaracaktır. Emin misiniz?',
      'transfer_ownership_confirm': 'Yönetici olacaksınız. Seçilen kullanıcı yeni sahip olacaktır.',
      'new_code_generated': 'Yeni davet kodu oluşturuldu!',
      'camera_permission_required': 'Kamera izni gereklidir.',
      'photo_permission_required': 'Fotoğraf kitaplığı izni gereklidir.',
      'mic_permission_required': 'Mikrofon izni gereklidir.',
      'speech_not_available': 'Ses tanıma bu cihazda kullanılamıyor.',
      'no_notes_yet': 'Henüz not yok.',
      'please_sign_in_notes': 'Notları kullanmak için lütfen giriş yapın.',
      'notes': 'Notlar',
      'save': 'Kaydet',
      'delete_location_title': 'Konumu Sil',
      'radius': 'Yarıçap',
      'dont_remind_after': 'Şu zamandan sonra hatırlatma',
      'pick_location_first': 'Lütfen önce bir konum arayın veya seçin.',
      'enter_label': 'Lütfen bir etiket girin.',
      'fetching_location': 'Cihaz konumu alınıyor...',
      'debug_disabled_release': 'Hata ayıklama araçları sürüm yapılarında devre dışıdır.',
      'no_triggers_today': 'Bugün tetikleme yok.',
      'no_locations_saved': 'Kayıtlı konum yok.',
      'export_summary': 'Özeti Dışa Aktar',
      'skip_reasons': 'ATLAMA NEDENLERİ',
      'map_placeholder': 'Harita Yer Tutucu (henüz gerçek harita yok)',
      'map': 'Harita',
      'alerts_placeholder': 'Uyarılar Yer Tutucu',
      'alerts': 'Uyarılar',
      'no_team': '— Ekip yok —',
      'select_team': 'Bir ekip seçin',
      'time_conflict': 'Zaman Çakışması',
      'save_anyway': 'Yine de Kaydet',
      'select_task_link': 'Bağlanacak bir görev seçin',
      'no_linked_task': '— Bağlı görev yok —',
      'delete_event': 'Etkinliği Sil',
      'action_undone_warning': 'Bu işlem geri alınamaz.',
      'task_detail': 'Görev Detayı',
      'task_detail_placeholder': 'Görev Detayı Yer Tutucu',
      'error_prefix': 'Hata: {message}',
      'add_task': 'Görev Ekle',
      'last_sync': 'Son senkronizasyon: {date}',
      'connected_at': 'Bağlanma zamanı: {date}',
      'synced_from_team': 'Ekip ile senkronize',
      'balance_your_life': 'Hayatınızı dengeleyin.',
      'add_note': 'Not Ekle',
      'edit_note': 'Notu Düzenle',
      'unnamed': 'İsimsiz',
      'title': 'Başlık',
      'content': 'İçerik',
      'disconnected': 'Bağlantı kesildi',
      'account': 'hesap',
      'disconnect_failed': 'Bağlantı kesme başarısız: {error}',
      'failed_to_create_event': 'Etkinlik oluşturulamadı: {error}',
      'geofence_debug_tool': 'Geofence Hata Ayıklama Aracı',
      'geofences': 'COĞRAFİ ÇİTLER',
      'last_trigger_logs': 'SON 10 TETİKLEME KAYDI (bugün)',
      'simulate_enter': 'Giriş Simüle Et',
      'simulate_exit': 'Çıkış Simüle Et',
      'inside': 'İÇERİDE',
      'outside': 'DIŞARIDA',
      'sent': '✓ gönderildi',
      'skipped': '✗ {reason}',
      'edit_location': 'Konumu Düzenle',
      'search_address_hint': 'Adres ara…',
      'address_not_found': 'Adres bulunamadı. Farklı bir sorgu deneyin.',
      'location_label_hint': 'Etiket (örn. Okul, Spor Salonu, Market)',
      'on_arrival': 'Varışta',
      'on_leave': 'Ayrılırken',
      'not_set': 'Ayarlanmadı',
      'save_changes': 'Değişiklikleri Kaydet',
      'save_location': 'Konumu Kaydet',
      'locations': 'Konumlar',
      'show_map': 'Haritayı Göster',
      'saved_locations': 'Kayıtlı Konumlar',
      'you_are_here': 'Buradasınız',
      'radius_m': '{radius} m yarıçap',
      'pin_on_map_hint': 'Konum iğnelemek için haritaya dokunun',
      'pin_on_map': 'Haritada İşaretle',
      'edit': 'Düzenle',
      'delete_location_confirm': '"{label}" konumunu kayıtlı konumlardan silmek istiyor musunuz?',
      'no_locations_yet': 'Henüz kayıtlı konum yok.\nBir tane eklemek için haritaya dokunun.',
      'get_started': 'Hemen Başla',
      'tagline': 'Alışkanlıklar edin.\nBilinçli yaşa.',
      'notification_channel_location_name': 'Konum Uyarıları',
      'notification_channel_team_name': 'Ekip Güncellemeleri',
      'notification_channel_team_desc': 'Ekip panosu değişiklikleri için bildirimler',
      'notification_arrived_at': '📍 {location} konumuna varıldı',
      'notification_left': '👋 {location} konumundan ayrılındı',
      'notification_arrived_body': '{location} konumuna vardınız! Görevlerinizi buradan kontrol edin.',
      'notification_left_body': '{location} konumundan ayrıldınız.',
      'notification_reminder_title': '⏰ Hatırlatıcı: {location}',
      'notification_reminder_body': '{location} konumuna 30 dakika önce vardınız. Görevlerinizi unutmayın!',
      'ai_config_error': 'Sistem yapılandırması eksik (API Key bulunamadı).',
      'ai_default_response': 'İşlem tamam.',
      'ai_error_generic': 'Bir hata oluştu.',
    },
  };

  static String of(String key, {Map<String, String>? args}) {
    final lang = localeNotifier.value.languageCode;
    String res = _data[lang]?[key] ?? _data['en']?[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        res = res.replaceAll('{$k}', v);
      });
    }
    return res;
  }
}

class LanguageSwitcher extends StatelessWidget {
  const LanguageSwitcher({super.key});

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<Locale>(
      valueListenable: localeNotifier,
      builder: (context, locale, _) {
        return DropdownButton<String>(
          value: locale.languageCode,
          dropdownColor: const Color(0xFF1A1200),
          underline: const SizedBox(),
          icon: const Icon(Icons.language, color: Color(0xFFFFB300), size: 20),
          items: const [
            DropdownMenuItem(value: 'en', child: Text('English', style: TextStyle(color: Colors.white))),
            DropdownMenuItem(value: 'tr', child: Text('Türkçe', style: TextStyle(color: Colors.white))),
          ],
          onChanged: (val) {
            if (val != null) localeNotifier.value = Locale(val);
          },
        );
      },
    );
  }
}
